name: Build
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.2.2]
        database: [mysql, postgres, sqlite, mssql]
    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 33060:3306
        options: --health-cmd "mysql -h localhost -e \"select now()\"" --health-interval 1s --health-timeout 5s --health-retries 30
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
        ports:
          - 55432:5432
      mssql:
        image: mcr.microsoft.com/azure-sql-edge:1.0.4
        env:
          SA_PASSWORD: yourStrongPassword123
          ACCEPT_EULA: Y
        ports:
          - 11433:1433
    env:
      TARGET_DB: ${{ matrix.database }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install native dependencies
        run: sudo apt install freetds-dev freetds-bin
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Setup test database
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bin/rails test
      - name: Run tests with separate connection
        run: SEPARATE_CONNECTION=1 bin/rails test
